tap "homebrew/bundle"
brew "openssl@3"
brew "chruby"
brew "ffmpeg"
brew "git-delta"
brew "mercurial"
brew "neovim"
brew "ruby-install"
brew "the_silver_searcher"
brew "tmux"
brew "zsh"

cask "google-cloud-sdk"
