#!/usr/bin/env bash

USERNAME=$(id -un)

progressln () {
  progress "$1\n"
}

progress () {
  printf "\n\e[1;32m***\e[0m\e[1m $1\e[0m"
}

# install packages
progress "Installing packages..."
if [ "$(uname -s)" = "Darwin" ]; then
  # macOS: homebrew
  progress "macOS detected!"
  progress "Checking if homebrew is installed..."

  if command -v brew > /dev/null; then
    echo "yes"
  else
    echo "no"
    progressln "installing Homebrew..."
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  fi

  progressln "Finished setting up Homebrew!"
  progressln "don't forget to run \`./afterbrew\` after running this script!"
else
  # linux: mainly debian
  progress "Something other than macOS detected!"
  progress "Checking if it's debian... "

  if command -v apt-get 2> /dev/null; then
    progressln "Installing packages with apt..."
    sudo apt install -y zsh neovim ffmpeg ssh silversearcher-ag git mercurial gcc g++ cmake automake curl wget make
  else
    echo "no"
    progressln "Sangwon isn't using debian? NO WAY!"

    if ! command -v curl > /dev/null; then
      progress "it seems like there isn't curl installed on this system."
      progressln "Please install it to continue..."
      bash
    fi
  fi

  ./afterbrew
fi

# install antigen
progressln "Installing antigen..."
sudo mkdir -p /usr/local/share/antigen
sudo chown $USERNAME /usr/local/share/antigen
curl -L git.io/antigen > /usr/local/share/antigen/antigen.zsh

progressln "Setting up dotfiles..."
./setup-dotfiles

# Install ruby
progressln "Installing ruby..."
./bin/getruby $RUBY_VERSION
