#!/usr/bin/env bash

RUBY_INSTALL_VERSION=0.7.0
CHRUBY_VERSION=0.3.9
USERNAME=$(id -un)

# Installing other pacakges; this only works on debian/ubuntu
# I'm assuming git and ssh are already installed on this system
# to clone this repository
echo -n "Checking if you're on debian... "

if command -v apt-get 2> /dev/null; then
  echo "OK! Let's install some packages."
  sudo apt install zsh neovim ffmpeg ssh silversearcher-ag git mercurial gcc g++ cmake automake
else
  echo "nope\n"
  echo "Sangwon isn't using debian? NO WAY!"
fi

# install ruby-install
wget -O ruby-install-$RUBY_INSTALL_VERSION.tar.gz https://github.com/postmodern/ruby-install/archive/v$RUBY_INSTALL_VERSION.tar.gz
tar -xzvf ruby-install-$RUBY_INSTALL_VERSION.tar.gz
cd ruby-install-$RUBY_INSTALL_VERSION/
sudo make install
cd .. && rm -rf ruby-install-$RUBY_INSTALL_VERSION

# install chruby
wget -O chruby-$CHRUBY_VERSION.tar.gz https://github.com/postmodern/chruby/archive/v$CHRUBY_VERSION.tar.gz
tar -xzvf chruby-$CHRUBY_VERSION.tar.gz
cd chruby-$CHRUBY_VERSION/
PREFIX=/usr/local/opt/chruby sudo make install
echo $PREFIX
cd .. && rm -rf chruby-$CHRUBY_VERSION 

# install antigen
sudo mkdir -p /usr/local/share/antigen
sudo chown $USERNAME /usr/local/share/antigen
curl -L git.io/antigen > /usr/local/share/antigen/antigen.zsh

# install Vundlevim
echo "\nChecking if VundleVim is installed..."

if [ -d "$HOME/.vim/bundle/Vundle.vim" ]; then
  echo "Looks like VundleVim is already installed!"
else
  echo "Installing VundleVim..."
  git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
fi

echo "\nSetting up dotfiles..."
./setup-dotfiles

# Install ruby
echo "\nInstalling Ruby..."
./bin/getruby "ruby-`cat ruby-version`"
