#!/usr/bin/env zsh

# install Homebrew
echo -n "Checking if homebrew is installed... "

if which brew; then
  echo "Looks like brew is already installed!"
else
  echo "Installing Homebrew..."
  /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

# install Vundlevim
echo "\nChecking if VundleVim is installed..."

if [ -d "$HOME/.vim/bundle/Vundle.vim" ]; then
  echo "Looks like VundleVim is already installed!"
else
  echo "Installing VundleVim..."
  git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
fi

echo "\nInstalling some packages..."
# install other usual stuff
brew install nvim tmux zsh ffmpeg antigen chruby ruby-install ag
brew cask install google-cloud-sdk

echo "\nSetting up dotfiles..."
./setup-dotfiles

# Install ruby
echo "\nInstalling Ruby..."
./bin/getruby "ruby-`cat ruby-version`"
