#!/bin/sh

rm ~/.bin

ln -fs $PWD/zshrc ~/.zshrc
ln -fs $PWD/tmux.conf ~/.tmux.conf
ln -fs $PWD/tmuxline ~/.tmuxline

mkdir ~/.config/nvim
ln -fs $PWD/nvim/init.lua ~/.config/nvim/init.lua
ln -fs $PWD/nvim/lua ~/.config/nvim/lua

ln -fs $PWD/ruby-version ~/.ruby-version
ln -fs $PWD/pryrc.rb ~/.pryrc

ln -fs $PWD/gitconfig ~/.gitconfig
ln -fs $PWD/gitignore ~/.gitignore_global

ln -fs $PWD/bin ~/.bin
